name: AWS FinOps Dashboard Report

on:
  workflow_dispatch:

jobs:
  run-finops-dashboard:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for OIDC if using it
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4  # Using stable v4 instead of v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'none'  # Skip looking for requirements files
      
      - name: Install dependencies
        run: pip install aws-finops-dashboard
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2  # More widely supported version
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Run AWS FinOps Dashboard
        run: |
          mkdir -p reports
          aws-finops \
            --all \
            --report-name finops-report \
            --report-type csv \
            --dir ./reports \
            --log-level info
      
      - name: Upload reports
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: finops-reports
          path: ./reports/*