name: AWS FinOps Dashboard

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'info'
      tags:
        description: 'Test scenario tags'
        required: false

jobs:
  run-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aws-finops-dashboard

      - name: Run AWS FinOps Dashboard
        run: |
          aws-finops-dashboard --log-level ${{ github.event.inputs.logLevel }} --tags ${{ github.event.inputs.tags }}
