name: AWS FinOps Dashboard Report

on:
  workflow_dispatch:

jobs:
  run-finops-dashboard:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for OIDC if using it
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4  # Using stable v4 instead of v5
        with:
          python-version: '3.11'
          # Removing the cache option completely
      
      - name: Install dependencies
        run: pip install aws-finops-dashboard
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Set up AWS CLI profile
        run: |
          # Explicitly create a named profile for aws-finops-dashboard
          mkdir -p ~/.aws
          
          # Create the credentials file
          cat > ~/.aws/credentials << EOF
          [default]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region = us-east-1
          EOF
          
          # Create the config file
          cat > ~/.aws/config << EOF
          [default]
          region = us-east-1
          output = json
          EOF
          
          # Verify AWS configuration
          aws sts get-caller-identity
      
      - name: Run AWS FinOps Dashboard
        run: |
          mkdir -p reports
          aws-finops \
            --all \
            --report-name finops-report \
            --report-type csv \
            --dir ./reports
      
      - name: Upload reports
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: finops-reports
          path: ./reports/*