name:  Destroy eks cluster

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "destroy" to confirm'
        required: true

jobs:
  destroy:
    if: github.event.inputs.confirm == 'destroy'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: hashicorp/setup-terraform@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: List EKS clusters
        run: aws eks list-clusters --region eu-north-1

      - name: Terraform Init
        working-directory: ./terraform/infra
        run: |
          terraform init \
            -backend-config="bucket=thereson-pdk" \
            -backend-config="key=eks/terraform.tfstate" \
            -backend-config="region=eu-north-1"

      - name: Terraform Destroy
        working-directory: ./terraform/infra
        run: terraform destroy -auto-approve
      